# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-workflow-job:
    steps:
    - name: A previous step
      id: previous-step
      uses: <an-action>
    - name: Convert a url
      id: convert-to-raw-url
      # or actioncloud/github-raw-url@master
      uses: actioncloud/github-raw-url@v1
      with:
        github-url: ${{ previous-step.outputs.github-url }}
    - name: Another step
      uses: <another-action>
      with:
        github-raw-url: ${{ convert-to-raw-url.outputs.raw-url }}
